### ISSUE TITLE
 TS2304: Cannot find name 'Promise'.

### ISSUE THREAD

**Issue by adamchenwei** [dabit3/create-xp-app#2]
Idea why its happening when I do `npm run web-watch`

System: MacOS Sierra
Node: 6.9.5

![screen shot 2017-05-08 at 11 48 31 am](https://cloud.githubusercontent.com/assets/4201698/25812454/5a344210-33e4-11e7-9380-7d40b2312111.png)

**Comment by adamchenwei** [comment]
Found a fix. change

`..."compilerOptions": {
    "target": "es5", ...`
es5 -> `es6`

**Comment by dabit3** [comment]
@adamchenwei thanks for the issue and the fix in the other repo! I appreciate your help :)
